name: Deploy to Hetzner
on:
  push:
    branches: [ main ] # Change this to 'master' if that is your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/backend_portfolio
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart portfolio